# Generated by Django 4.2.7 on 2023-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_skilmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('analysis', 'analysis'), ('flasks', 'flasks'), ('ideas', 'ideas')], max_length=50)),
                ('profession', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='image',
            field=models.ImageField(upload_to='home/'),
        ),
    ]
